name: ESP32 Portero
version: "1.0"
slug: esp32_portero
description: Servidor para recibir audio del ESP32 y exponerlo a Home Assistant
arch:
  - amd64
startup: services
boot: auto
ports:
  5000/tcp: 5000
options:
  host: 0.0.0.0
schema:
  host: str
image: local/esp32_portero
