name: "ESP32 Intercom Audio Server"
version: "1.0.0"
slug: "esp32_portero_audio"
description: "Servidor de audio para intercom basado en ESP32 (WebSocket + UDP)."
arch:
  - amd64
  - armv7
  - aarch64
  - i386

startup: services
boot: auto
homeassistant: "2023.0.0"

options: {}
schema: {}

ports:
  "8124/tcp": 8124   # WebSocket
  "8765/udp": 8765   # UDP audio

ports_description:
  "8124/tcp": "WebSocket server port"
  "8765/udp": "UDP audio port"

webui: "http://[HOST]:8124"
ingress: false
init: false
